travis:
  secure:
    BINSTAR_TOKEN: iwzbXX9PiDt1IuZJGEOSJfFxl8u59j6CgumKn4yYrOhl4QuBb/HElzK5FJZUAblEB84z4oCvsD7esTNfwHDEhYZCFnpm7w1BRoXTSqbOCEZ0tz7BLdUb+cjAtwgqxEZmzb9wJrrfcy+rQmfGA9qR11flIyb/qCmlYldrwYyU6tNfoTM45J4KYmiCI3Yrj8YjHL5cpKzjsowDidAtkLlf0SZaFuGTRN75EPuuorIWwSKM5+983WLcbdziex+YmNQpKQaviTPShSdKQp6ts1tWj2JLGcG3Ln5hk4HqBeorctKmIc4QKx/D9MTrOavcwLxXXYCHFpGkH9fC7GBE3ww1uMedG354Wo/Vj0y8gh9vzMtfr+LUa2NhgMhLZ3WseVZ3B/1cAD8pnjwimF3yc+0i7pUipQBw2exGaA+q/pdUh5uKPYs67OOxmTTT1Bb1834zaBWUOzVW+N4lUiF37yEWoNZQdxTro6scyR5A4lrrhMVpLPFcgV6QVngJ2HII3oY3SBxy8kea0UoLkac8Yh2BDTu0v+3629l0nbOoAq6V/rTSySzFkpnLPGTtfNbO59MnPLZopGNlZj5GvA38DALTVP73xPG3bfMI47ZLVyClZCdQfhECqNkJlPhlVMjqkuxqJ0HsJZ5XfvCPzeZX0VL8FQ6eU+lbZAztFWxgbiNlO0A=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
