travis:
  secure:
    BINSTAR_TOKEN: EwpwEn4j4JDDEiBw/mMLRHXikr5qz1cdroQOvjp1K2F41nAgoN4qE68CLKh4PDObX5iEHXsRNm45/xH+TyCXciu+OzmQl0o8R0vsNIIqpIFWyR1Nc99a1mMFWbcDegw+/eWwQcjlLxdqtBtzYh56gUJwkO+wzZ7TM0OzcyX9GAOm2lPLCQDgEkUmyOddl26iL9lVUmWl2Z00H05zOLozIhusTZMib/W0xXIaKDY6YnpN0PQhf6AhQu31QQmF6q+fUipteztB+156ve/CCHCYmv5ImfiXWL176/nph5tlY0x/x7bv/LblCK5u066t/nqlPZHCJxUzIJQ9PT5zI53qQqFWs1OpM9pbusxi2kef13m87W4+b8fJ7uB24kTZ62aIRL+iWxe0nvdw9uXp5yLY2B9ajPjc22riMiFOhutqonvMH8esHqvjXxwkArLLFVRozctOAxv/FSoT/arq16viH7Yy525vbMqEDwqlOQvuaJrsAdy2cB+ZcMOIjvlN5mtg0YbIflvO9atgXePXd7Nqe26thMMGBQFLGj0PuFQaIw+SIhqs51cZqYah+O0B5Ga3G/plB0aIpLq+Q+aMy2gMpkzo3FC1tmj2e8E5YP4Og9I/+n5OgTATnsFugjZtZTgk5ewAZ3ODA6amoT4e8ijw7uWLu/adGeNLpq/iWv32wDM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
